server:
  port: 8099
  servlet:
    context-path: /houcheng
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/spring-vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: 192.168.200.130
    port: 6379
    database: 0

#  jackson:
#    date-format: yy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.houcheng.emplate: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  ip: localhost




